### ISSUE TITLE
CP949 out of index error

### ISSUE THREAD

**Issue by ghts** [suapapa/go_hangul#2]
github.com/suapapa/go_hangul/encoding/cp949/cp949.go
in func (p *translateFromCp949) Translate() 
for len(data) > 0 { // <- allow length 1 data slice
...
n := uint16(data[0])<<8 | uint16(data[1]) // <- data[1] is out of index.
...
}

**Comment by suapapa** [comment]
Thanks!!! I'll fix it!

**Comment by suapapa** [comment]
Fixed to return error in the case.
Thanks.
