### ISSUE TITLE
AppendPostposition for (으)로

### ISSUE THREAD

**Issue by sublee** [suapapa/go_hangul#4]
Thanks for the very useful library to manipulate Hangul letters.

`AppendPostposition()` takes the allomorphs of a postposition at `with` and `without`. The choice between `with` and `without` depends on only the prior final consonant. This implementation works well and is enough in most cases. But there's one exception.

`(으)로` becomes `로` after a vowel. Also, it becomes `으로` after a final consonant EXCEPT `ㄹ`. After a final `ㄹ`, `(으)로` becomes `로`, not `으로`.

Check the below examples:

```
학교로 (로 after a final consonant)
집으로 (으로 after a vowel)
마을로 (로 after a final ㄹ)
```

**Comment by suapapa** [comment]
Thanks for reporting.
It fixed.

**Comment by sublee** [comment]
Thanks!

But the commit seems to break the backward compatibility. I commented at  https://github.com/suapapa/go_hangul/commit/a6c3aff70511c1fd5191622d43c52c11c1f6f571#r30192680.

**Comment by sublee** [comment]
I made a pull request for fixing it. https://github.com/suapapa/go_hangul/pull/5
